### ISSUE TITLE
Naming Folders and Files

### ISSUE THREAD

**Issue by Auleen** [PEC-CSS/PEC-Previous-Year-Papers#1]
the code for the scraping script uses basic links of facebook albums to capture the name of the album from its title.
some of the basic links are broken hence the folder name grabs "Error Facebook".
can someone find a way to directly grab the album names from the actual facebook links?
thanks !

**Comment by kavyarishi19** [comment]
did you try error handling ?
Try and Except

**Comment by Auleen** [comment]
have done that but that is only being used to save the files with some makeshift name. still not being able to grab the actual subject names.
