### ISSUE TITLE
Add home route to Pec Papers Logo

### ISSUE THREAD

**Issue by jagjit-1** [PEC-CSS/PEC-Previous-Year-Papers#24]
![image](https://user-images.githubusercontent.com/91937836/197016739-fedeb4a6-8d08-4e6a-8fa4-fae9640b3bc3.png)

**Resolve in dev branch**

**Comment by mgilberties** [comment]
Please can you assign this to me to have a go at?

**Comment by mgilberties** [comment]
@jagjit-1  Thanks for your patience, I had all the wrong accounts signed in and was a bit up the wall. I have now made my pull request on the dev branch on a fork. Hopefully this will allow you to review and merge?

Many thanks.
