### ISSUE TITLE
Add a readme for the project

### ISSUE THREAD

**Issue by jagjit-1** [PEC-CSS/PEC-Previous-Year-Papers#28]
Readme should illustrate following points-
1. How to run the project (npm start commands etc)
2. How to contribute to the project (diff GitHub commands etc)
3. What the project is about (description provided below)

**About the project** - Pec Paper is an open source project started to help pec students find previous year paper in one place hence helping them to prepare for exams 

PS - if someone is wondering what the hell is pec its Punjab Engineering College xd

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by jagjit-1** [comment]
Sure, assigning it to you
